function A = importfile(filename, delimiter, format, startRow, endRow)
% Example:
%   A(:,2) = importfile1('156p25M.csv', ',' , '%f%f');
%   A(:,3) = importfile1('156p25M.csv', ',' , '%f%f%f');
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/08/19 21:34:21

%% Initialize variables.
if nargin<=3
    startRow = 2;
    endRow = inf;
end

%% Open the text file.
fileID = fopen(filename,'r');

%% find file column numbers
ColNum=1;
tline=fgetl(fileID);
tline=fgetl(fileID);
for i=1:length(tline)
    ColNum=ColNum+strcmp(tline(i),Delimiter);
end
fclose(fileID);

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
for i=1:ColNum
    if(i==1)
        formatSpec=format;
    else
        formatSpec=strcat(formatSpec,format);
    end
end
formatSpec = strcat(formatSpec,'%[^\n\r]');
fileID=fopen(filename,'r');
%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
A=zeros(length(dataArray{:,1}),ColNum);
for i=1:ColNum
    A(:,i) = dataArray{:, i};
end


